/**
 * Props types for slide compositions.
 *
 * durationInFrames is injected by the Python backend.
 * It drives calculateMetadata so Remotion allocates exactly the right frames.
 */

/** Animation style variants (may be referenced by Freeform TSX code) */
export type AnimationStyle =
  | "default"       // Current behavior (backwards compatible)
  | "cascadeUp"     // All items slide up sequentially
  | "fadeAll"        // All items fade in simultaneously
  | "slideRight"    // All items slide from right
  | "bounceIn"      // Bouncy spring entrance
  | "zoomPop";      // Scale overshoot entrance

/** Common fields injected by Python — not generated by AI */
interface WithDuration {
  durationInFrames?: number;
  /** B-roll image filename in public/ (e.g. "_bg_001.png"). Injected by Python. */
  backgroundImage?: string;
  /** 1-based slide index for progress bar. Injected by Python. */
  slideIndex?: number;
  /** Total number of slides for progress bar. Injected by Python. */
  totalSlides?: number;
}

export interface FreeformProps extends Record<string, unknown>, WithDuration {
  template: "Freeform";
}

export type SlideProps = FreeformProps;

/** Default fallback: 5s at 30fps */
export const DEFAULT_SLIDE_FRAMES = 150;
